easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

api_login_check:
    path: /api/login_check

islam_sn_core:
    resource: "@IslamSnCoreBundle/Resources/config/routing.yml"
    prefix:   /

islam_sn_social:
    resource: "@IslamSnSocialBundle/Resources/config/routing.yml"
    prefix:   /

islam_sn_publication:
    resource: "@IslamSnPublicationBundle/Resources/config/routing.yml"
    prefix:   /

islam_sn_mosque:
    resource: "@IslamSnMosqueBundle/Resources/config/routing.yml"
    prefix:   /api/v1/mosque/

islam_sn_invocation:
    resource: "@IslamSnInvocationBundle/Resources/config/routing.yml"
    prefix:   /

islam_sn_user:
    resource: "@IslamSnUserBundle/Resources/config/routing.yml"
    prefix:   /utilisateur

app:
    resource: '@AppBundle/Controller/'
    type: annotation
