<?php

namespace IslamSn\MosqueBundle\Repository;

/**
 * PrayTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrayTabRepository extends \Doctrine\ORM\EntityRepository
{
}
